version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-portfolio
    ports:
      - "5000:4000"  # Map host port 5000 to container port 4000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb"
    depends_on:
      - db
    command: >
      sh -c "
      npx prisma migrate dev --name init &&
      npx prisma generate &&
      node src/server.js
      "

      
  db:
    container_name: postgres_db
    image: "postgres:latest"
    restart: always
    ports:
      - "9000:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

volumes:
  db_data:
